///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Account_Users
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Account_Users recording.
    /// </summary>
    [TestModule("34f0b140-37f7-41a8-9695-3cabc9eb2aad", ModuleType.Recording, 1)]
    public partial class Account_Users : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Account_UsersRepository repository.
        /// </summary>
        public static Account_UsersRepository repo = Account_UsersRepository.Instance;

        static Account_Users instance = new Account_Users();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Account_Users()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Account_Users Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.UserEmail' at 82;19.", repo.ApplicationUnderTest.UserEmailInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.UserEmail.Click("82;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'obs-admin{RShiftKey down}@{RShiftKey up}condenast.com' with focus on 'ApplicationUnderTest.UserEmail'.", repo.ApplicationUnderTest.UserEmailInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.UserEmail.PressKeys("obs-admin{RShiftKey down}@{RShiftKey up}condenast.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.UserPassword' at 111;18.", repo.ApplicationUnderTest.UserPasswordInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.UserPassword.Click("111;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'password' with focus on 'ApplicationUnderTest.UserPassword'.", repo.ApplicationUnderTest.UserPasswordInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.UserPassword.PressKeys("password");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Loginbutton' at 128;16.", repo.ApplicationUnderTest.LoginbuttonInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Loginbutton.Click("128;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AccountUsers' at 43;9.", repo.ApplicationUnderTest.AccountUsersInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.AccountUsers.Click("43;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.NewAccountUser' at 37;10.", repo.ApplicationUnderTest.NewAccountUserInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.NewAccountUser.Click("37;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CreateAccountUser' at 112;12.", repo.ApplicationUnderTest.CreateAccountUserInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.CreateAccountUser.Click("112;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '5' on item 'ApplicationUnderTest.AccountUserAccountId'.", repo.ApplicationUnderTest.AccountUserAccountIdInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.AccountUserAccountId.Element.SetAttributeValue("TagValue", "5");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CreateAccountUser' at 96;20.", repo.ApplicationUnderTest.CreateAccountUserInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.CreateAccountUser.Click("96;20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '2' on item 'ApplicationUnderTest.AccountUserDefaultDataSourceId'.", repo.ApplicationUnderTest.AccountUserDefaultDataSourceIdInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.AccountUserDefaultDataSourceId.Element.SetAttributeValue("TagValue", "2");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '14' on item 'ApplicationUnderTest.AccountUserUserId'.", repo.ApplicationUnderTest.AccountUserUserIdInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.AccountUserUserId.Element.SetAttributeValue("TagValue", "14");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CreateAccountUser' at 92;16.", repo.ApplicationUnderTest.CreateAccountUserInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.CreateAccountUser.Click("92;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AccountUsers' at 70;12.", repo.ApplicationUnderTest.AccountUsersInfo, new RecordItemIndex(13));
            repo.ApplicationUnderTest.AccountUsers.Click("70;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '5' on item 'ApplicationUnderTest.AccountIdfiltter'.", repo.ApplicationUnderTest.AccountIdfiltterInfo, new RecordItemIndex(14));
            repo.ApplicationUnderTest.AccountIdfiltter.Element.SetAttributeValue("TagValue", "5");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Filtterbutton' at 35;8.", repo.ApplicationUnderTest.FiltterbuttonInfo, new RecordItemIndex(15));
            repo.ApplicationUnderTest.Filtterbutton.Click("35;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '14' on item 'ApplicationUnderTest.UserIdfiltter'.", repo.ApplicationUnderTest.UserIdfiltterInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.UserIdfiltter.Element.SetAttributeValue("TagValue", "14");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Filtterbutton' at 28;14.", repo.ApplicationUnderTest.FiltterbuttonInfo, new RecordItemIndex(17));
            repo.ApplicationUnderTest.Filtterbutton.Click("28;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndexTableAccountUsers.View' at 7;5.", repo.ApplicationUnderTest.IndexTableAccountUsers.ViewInfo, new RecordItemIndex(18));
            repo.ApplicationUnderTest.IndexTableAccountUsers.View.Click("7;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AccountUsers' at 47;4.", repo.ApplicationUnderTest.AccountUsersInfo, new RecordItemIndex(19));
            repo.ApplicationUnderTest.AccountUsers.Click("47;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '14' on item 'ApplicationUnderTest.UserIdfiltter'.", repo.ApplicationUnderTest.UserIdfiltterInfo, new RecordItemIndex(20));
            repo.ApplicationUnderTest.UserIdfiltter.Element.SetAttributeValue("TagValue", "14");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Filtterbutton' at 33;14.", repo.ApplicationUnderTest.FiltterbuttonInfo, new RecordItemIndex(21));
            repo.ApplicationUnderTest.Filtterbutton.Click("33;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndexTableAccountUsers.Edit' at 8;3.", repo.ApplicationUnderTest.IndexTableAccountUsers.EditInfo, new RecordItemIndex(22));
            repo.ApplicationUnderTest.IndexTableAccountUsers.Edit.Click("8;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '16' on item 'ApplicationUnderTest.AccountUserUserId'.", repo.ApplicationUnderTest.AccountUserUserIdInfo, new RecordItemIndex(23));
            repo.ApplicationUnderTest.AccountUserUserId.Element.SetAttributeValue("TagValue", "16");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CreateAccountUser' at 85;14.", repo.ApplicationUnderTest.CreateAccountUserInfo, new RecordItemIndex(24));
            repo.ApplicationUnderTest.CreateAccountUser.Click("85;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AccountUsers' at 55;8.", repo.ApplicationUnderTest.AccountUsersInfo, new RecordItemIndex(25));
            repo.ApplicationUnderTest.AccountUsers.Click("55;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '16' on item 'ApplicationUnderTest.UserIdfiltter'.", repo.ApplicationUnderTest.UserIdfiltterInfo, new RecordItemIndex(26));
            repo.ApplicationUnderTest.UserIdfiltter.Element.SetAttributeValue("TagValue", "16");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Filtterbutton' at 34;14.", repo.ApplicationUnderTest.FiltterbuttonInfo, new RecordItemIndex(27));
            repo.ApplicationUnderTest.Filtterbutton.Click("34;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Logout' at 18;11.", repo.ApplicationUnderTest.LogoutInfo, new RecordItemIndex(28));
            repo.ApplicationUnderTest.Logout.Click("18;11");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
